// <auto-generated />
using System;
using CaptivePortal.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaptivePortal.Database.Migrations
{
    [DbContext(typeof(CaptivePortalDbContext))]
    [Migration("20231222034322_Devices")]
    partial class Devices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CaptivePortal.Database.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountingSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AuthorizedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("CallingStationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceIpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceMac")
                        .HasColumnType("TEXT");

                    b.Property<string>("NasIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("NasIpAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CaptivePortal.Database.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("CaptivePortal.Database.Entities.Device", b =>
                {
                    b.HasOne("CaptivePortal.Database.Entities.Person", "Person")
                        .WithMany("Devices")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CaptivePortal.Database.Entities.Person", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
